services:
  postgres:
    container_name: postgres_linker
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linker
    ports:
      - "5432:5432"
    restart: always
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_linker
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: superdupersecretpassword
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    restart: always
volumes:
  minio_data:
